logging:
  level:
    root: INFO
    com.home.m1service: DEBUG
    com.home.m3service: DEBUG
    org.springframework.cloud.kubernetes: DEBUG

spring:
  application:
    name: m3-service
  config:
    import:
      - "kubernetes:"
      - "optional:consul:"
      - "optional:vault:"
  cloud: # -> MOVED TO 'configmap-k8s.yaml': default k8s profile 'application-kubernetes' for all services
    kubernetes:
      enabled: true
      config:
        enabled: true
        enableApi: true
        namespace: sample-mcs
        name: ${spring.application.name}
        includeProfileSpecificSources: true
        sources:
          - name: application
          - name: ${spring.application.name}
      secrets:
        enabled: false
        enableApi: false
        namespace: sample-mcs
#        name: ${spring.application.name}
#        includeProfileSpecificSources: true
#        sources:
#          - name: application
#          - name: ${spring.application.name}
      reload:
        enabled: true
        strategy: refresh
        mode: polling
        period: 40s
      discovery:
        enabled: false
        all-namespaces: false
        namespace: sample-mcs
    consul:
      enabled: false
      host: ${SPRING_CLOUD_CONSUL_HOST}
      port: ${SPRING_CLOUD_CONSUL_PORT}
      config:
        format: YAML
        enabled: false
        fail-fast: true
        default-context: application
      discovery:
        enabled: true
        register: true
        prefer-ip-address: false
        health-check-interval: 5s
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}-${HOSTNAME}
    vault:
      enabled: false
      fail-fast: true
      uri: http://${SPRING_CLOUD_VAULT_HOST}:8200
      token: ${SPRING_CLOUD_VAULT_TOKEN}
      kv:
        enabled: false
        backend: secret
        profile-separator: /
        default-context: application

management:
  health:
    kubernetes:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always