logging:
  level:
    root: INFO
    com.home.m1service: DEBUG
    com.home.m3service: TRACE
  pattern:
    console: "%d{d-MMM-yyyy HH:mm:ss.SSS}ms [%thread] [%-5level | %logger{1}]@> %msg%n" # static

cs.properties:
  m-name: IamDev