logging:
  level:
    root: INFO
    com.home.m1service: DEBUG
    com.home.m3service: TRACE
    org.springframework.cloud.vault: DEBUG
  pattern: # static, can not be changed in runtime
    console: "%d{d-MMM-yyyy HH:mm:ss.SSS}ms [%thread] [tr=%X{traceId}, sp=%X{spanId}] [%-5level | %logger{1}]@> %msg%n"

cs.properties:
  m-name: IamDev