# http://localhost:8888/cs-config-server/default

logging.level:
  # to reduce log noise
  org.springframework.cloud.config.server.environment.NativeEnvironmentRepository: warn
  org.springframework.cloud.config.server.environment: debug # MultipleJGitEnvironmentRepository
  org.springframework.cloud.config.server.support.GitCredentialsProviderFactory: warn

spring:
  application:
    name: cs-configServer