spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vv-golovkov/config-repo.git
          default-label: main
          searchPaths:
            - "{application}"
            - "." # але канфіги з {application} мають пріоритет перез кореневими
          refresh-rate: 30 # automatic 'git fetch' each N-seconds (OPTIONAL)
          # username: your-git-username (for private repo only)
          # password: your-git-password-or-token (for private repo only)