name: vg-ci-pipeline

env:
  PROFILE: dev
  GIT_COMMIT: ${{ github.sha }}

on:
  push:
    # branches:
    # - main
    tags:
      - 'R*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: vg-checkout-code
        uses: actions/checkout@v5

      - name: vg-setup-docker-build
        uses: docker/setup-buildx-action@v3

      - name: vg-start-consul-vault
        run: |
          docker compose up -d cs-consul cs-vault

      - name: vg-load-kv-consul-vault
        run: |
          chmod +x ./x_config/load-kv.sh
          ./x_config/load-kv.sh

      - name: vg-build-start-other-services
        run: |
          docker compose up --build -d --scale m1-service=2 --scale m3-service=2

      - name: vg-show-running-containers
        run: docker ps -a

        # ----- Another option to run everything in one shot (but remove redundant lines from there) -----
        # - name: vg-run-sh
        # run: |
        # chmod +x ./run.sh
        # ./run.sh