name: vg-ci-pipeline
env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}
on:
  release:
    types:
      - published
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: ci-checkout-code
        uses: actions/checkout@v5
      - name: ci-setup-docker
        uses: docker/setup-buildx-action@v3
      - name: ci-login-ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.IMAGE_NAMESPACE }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: ci-build-images
        run: docker compose build
      - name: ci-push-images
        run: docker compose push
      - name: ci-show-images
        run: docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}" | grep "${IMAGE_NAMESPACE}"||echo "NtFnd"
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: false # skip 'cd' job as GitHub can not connect to local k8s, as It is not globally available
    steps:
      - name: cd-checkout
        uses: actions/checkout@v5
      - name: cd-setup-kubectl
        uses: azure/setup-kubectl@v4
      - name: cd-setup-kustomize
        uses: imranismail/setup-kustomize@v1
      - name: cd-configure-kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      - name: cd-update-images
        working-directory: ./x_k8s/base
        run: |
          kustomize edit set image ghcr.io/vv-golovkov/m1-service=ghcr.io/vv-golovkov/m1-service:${RELEASE_TAG}
          kustomize edit set image ghcr.io/vv-golovkov/m3-service=ghcr.io/vv-golovkov/m3-service:${RELEASE_TAG}
      - name: cd-apply-k8s
        run: |
          kubectl apply -k ./x_k8s/base
      - name: cd-rollout-status
        run: |
          kubectl get deployments -n sample-mcs -o name | xargs -I {} kubectl rollout status {} -n sample-mcs