name: vg-ci-pipeline

env:
  GIT_COMMIT: ${{ github.sha }}
  PROFILE: dev
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: vg-checkout-code
        uses: actions/checkout@v5

      - name: vg-setup-docker-build
        uses: docker/setup-buildx-action@v3

      - name: vg-login-ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.IMAGE_NAMESPACE }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: vg-start-consul-vault
        run: docker compose up -d cs-consul cs-vault

      - name: vg-load-kv-consul-vault
        run: |
          chmod +x ./x_config/load-kv.sh
          ./x_config/load-kv.sh

      - name: vg-build-images
        run: docker compose build

      - name: vg-push-images
        run: docker compose push

      - name: vg-show-images
        run: |
          echo "==== Docker images for ${IMAGE_NAMESPACE} ===="
          docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}" | grep "${IMAGE_NAMESPACE}"||echo "No fnd"

      - name: vg-show-all-containers
        run: docker ps -a

        # ----- Another option to run everything in one shot (but remove redundant lines from there) -----
        # - name: vg-run-sh
        # run: |
        # chmod +x ./run.sh
        # ./run.sh